### ISSUE TITLE
Unable to disable source maps

### ISSUE THREAD

**Issue by alexanderjakob** [SymfonyCasts/sass-bundle#58]
Hey everybody,

I'm trying to disable the output of the link to a source map URL - I don't want to have a source map comment in my generated CSS file. My first thought was: this is easy, just set inside sass_options node `source_map: false` - didn't work. Ok, just set `embed_source_map: false`  - didn't work.

`Command: '/var/www/html/var/dart-sass/sass' '/var/www/html/assets/website/styles/main.scss:/var/www/html/var/sass/main.output.css' '--style=expanded' '--no-source-map' '--no-embed-source-map'`

`--embed-source-map isn't allowed with --no-source-map.`

So, it seems that the combination of these options is not allowed - can you guys help me out and tell me how to disable it.

Thank you in advance!

**Comment by bocharsky-bw** [comment]
As I understand Sass complains about this? If so, then the question is probably to Sass not to this bundle.

About this:
> source_map: false - didn't work

IIRC that's exactly what add that `--no-source-map` option in your command dump. Also you say "--embed-source-map isn't allowed with --no-source-map" but in your command I see you don't have that `--embed-source-map` but have `--no-embed-source-map` instead?  

Could you just try to pick up the options that fit your needs by executing that  internal`/var/www/html/var/dart-sass/sass' '/var/www/html/assets/website/styles/main.scss:/var/www/html/var/sass/main.output.css' '--style=expanded'` command manually? As soon as you have correct options - you just need to set them in the Sass bundle config and it should work I think, because the bundle just converts that config into those options like `--source-map`/`--no-source-map`, nothing special

**Comment by alexanderjakob** [comment]
Thank you, @bocharsky-bw 

I tried following code
`/var/www/html/var/dart-sass/sass '/var/www/html/assets/website/styles/main.scss:/var/www/html/var/sass/main.output.css' '--style=expanded'`

My css file has a sourcemap link in it - I don't want that. 👎 

I tried the following code
`/var/www/html$ /var/www/html/var/dart-sass/sass '/var/www/html/assets/website/styles/main.scss:/var/www/html/var/sass/main.output.css' '--style=expanded' '--no-source-map'`

My css file has no sourcemap link in it - I really want that 👍 

--

My point is that it seems, that these options `--[no-]source-map` and `--[no-]embed-source-map` are always added because of missing possibility to really disable the option via symfonycasts_sass.yaml file. If I set it to false like so:

```yaml
symfonycasts_sass:
    sass_options:
        source_map: false
        style: expanded
```

it is added as ` '/var/www/html/var/dart-sass/sass' '/var/www/html/assets/website/styles/main.scss:/var/www/html/var/sass/main.output.css' '--style=expanded' '--no-source-map' '--embed-source-map'` with an `embed-source-map` option (due to default value behavior I think, [see here](https://github.com/SymfonyCasts/sass-bundle/blob/2f2fd8b89ae89dc314fb5445bbbbbce4ae456e51/src/DependencyInjection/SymfonycastsSassExtension.php#L113)).

Because these options always have to be a boolean value it is currently not possible to disable it at all (e.g. `source_map: null`) and there are always options set.

**Comment by smnandre** [comment]
I'm sorry i believed i sorted this .... but it reality i did not. 

2 things:

i do believe this option (embed source maps) should be without default (especially because with AssetMapper the source maps do not work so..)

To fix things, i can hard-code a test to remove the 2 source maps options if sourcemap is false ? 

wdyt @bocharsky-bw ?

**Comment by bocharsky-bw** [comment]
Hm, I'm not sure I got it... OK, `embed_source_map` has a default value, but you can override it with a custom value, no? Or setting `embed_source_map` to `false` does not work somehow? We ignore the value from the config?

**Comment by smnandre** [comment]
I'll do that

**Comment by bocharsky-bw** [comment]
Hey @alexanderjakob 

Could you give #59 a try, please? Does it solve your problem?

**Comment by alexanderjakob** [comment]
Works perfectly, great job, thank you guys!
